- name: Example Playbook
  hosts: all
  
  tasks:
    - name: arun
      ansible.windows.win_copy:
        src: files/piprequirements.txt
        dest: C:\piprequirements.txt
          # mode: '0644' 

