- name: Example Playbook
  hosts: all
  
  tasks:
    - name: Create pip requirements file
      copy:
        src: piprequirements.txt
        dest: C:\piprequirements.txt
        mode: '0700'
     




