- name: Example Playbook
  hosts: all
  
  tasks:
    - name: Create pip requirements file
      copy:
        src: files/piprequirements.txt
        dest: C:\piprequirements.txt
        mode: '0700'
      vars:
        ansible_python_interpreter: /path/to/python        